-- Run this entire file once in Supabase SQL Editor.
-- Activity scores are calculated from real profile and interaction data.

create table if not exists public.activity_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  checkin_date date not null default ((now() at time zone 'Asia/Shanghai')::date),
  created_at timestamptz not null default now(),
  unique (user_id, checkin_date)
);

alter table public.activity_checkins enable row level security;
grant select, insert on public.activity_checkins to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "users read own activity checkins" on public.activity_checkins;
drop policy if exists "users add own activity checkins" on public.activity_checkins;
create policy "users read own activity checkins" on public.activity_checkins
  for select to authenticated using (auth.uid() = user_id or public.is_blog_admin());
create policy "users add own activity checkins" on public.activity_checkins
  for insert to authenticated with check (auth.uid() = user_id);

create or replace function public.activity_title(p_score integer)
returns text
language sql
immutable
as $$
  select case
    when p_score >= 4000 then '罗客神'
    when p_score >= 2000 then '全站星使'
    when p_score >= 1000 then '罗客星使'
    when p_score >= 800 then '拾星罗客'
    when p_score >= 500 then '拾光罗客'
    when p_score >= 300 then '深知罗者'
    when p_score >= 200 then '熟知罗者'
    when p_score >= 100 then '知罗者'
    when p_score >= 50 then '漂泊者'
    else '初入人'
  end;
$$;

create or replace function public.calculate_user_activity(p_user_id uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select greatest(0,
    10
    + case when nullif(btrim(p.mbti), '') is not null then 20 else 0 end
    + case when nullif(btrim(p.gender), '') is not null then 10 else 0 end
    + case when jsonb_typeof(coalesce(p.personal_tags, '[]'::jsonb)) = 'array'
             and jsonb_array_length(coalesce(p.personal_tags, '[]'::jsonb)) > 0 then 20 else 0 end
    + 20 * (select count(*)::integer from public.activity_checkins c where c.user_id = p_user_id)
    + 5 * (select count(*)::integer from public.post_likes l where l.user_id = p_user_id)
    + 5 * (select count(*)::integer from public.content_likes l where l.user_id = p_user_id)
    + 5 * (select count(*)::integer from public.post_comments c where c.user_id = p_user_id)
    + 5 * (select count(*)::integer from public.content_comments c where c.user_id = p_user_id)
    + 5 * (select count(*)::integer from public.whispers w where w.user_id = p_user_id)
  )::integer
  from public.profiles p
  where p.id = p_user_id;
$$;

create or replace function public.has_activity_access(p_required integer)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_blog_admin() or coalesce(public.calculate_user_activity(auth.uid()), 0) >= p_required;
$$;

create or replace function public.get_my_activity_status()
returns table (
  score integer,
  title text,
  checked_today boolean,
  next_score integer,
  next_title text
)
language sql
stable
security definer
set search_path = public
as $$
  with current_score as (
    select coalesce(public.calculate_user_activity(auth.uid()), 0)::integer as value
  )
  select
    value,
    public.activity_title(value),
    exists(
      select 1 from public.activity_checkins
      where user_id = auth.uid()
        and checkin_date = (now() at time zone 'Asia/Shanghai')::date
    ),
    case
      when value < 50 then 50 when value < 100 then 100 when value < 200 then 200
      when value < 300 then 300 when value < 500 then 500 when value < 800 then 800
      when value < 1000 then 1000 when value < 2000 then 2000 when value < 4000 then 4000
      else value
    end,
    case
      when value < 50 then '漂泊者' when value < 100 then '知罗者' when value < 200 then '熟知罗者'
      when value < 300 then '深知罗者' when value < 500 then '拾光罗客' when value < 800 then '拾星罗客'
      when value < 1000 then '罗客星使' when value < 2000 then '全站星使' when value < 4000 then '罗客神'
      else '罗客神'
    end
  from current_score;
$$;

create or replace function public.daily_activity_checkin()
returns table (score integer, title text, checked_today boolean)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception '请先登录'; end if;
  insert into public.activity_checkins (user_id, checkin_date)
  values (auth.uid(), (now() at time zone 'Asia/Shanghai')::date)
  on conflict (user_id, checkin_date) do nothing;
  return query select public.calculate_user_activity(auth.uid()), public.activity_title(public.calculate_user_activity(auth.uid())), true;
end;
$$;

create or replace function public.list_activity_leaderboard()
returns table (
  user_id uuid,
  display_name text,
  avatar_url text,
  is_admin boolean,
  score integer,
  title text,
  rank bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with scores as (
    select p.id, coalesce(nullif(btrim(p.display_name), ''), '普通用户') as display_name,
      p.avatar_url, coalesce(p.is_admin, false) as is_admin,
      public.calculate_user_activity(p.id) as score
    from public.profiles p
  )
  select id, display_name, avatar_url, is_admin, score, public.activity_title(score),
    dense_rank() over (order by score desc, display_name asc)
  from scores
  order by score desc, display_name asc;
$$;

revoke all on function public.calculate_user_activity(uuid) from public;
revoke all on function public.daily_activity_checkin() from public;
grant execute on function public.activity_title(integer) to anon, authenticated;
grant execute on function public.calculate_user_activity(uuid) to authenticated;
grant execute on function public.has_activity_access(integer) to authenticated;
grant execute on function public.get_my_activity_status() to authenticated;
grant execute on function public.daily_activity_checkin() to authenticated;
grant execute on function public.list_activity_leaderboard() to anon, authenticated;

-- Ordinary users need 10 activity points to publish comments and whispers.
drop policy if exists "users add comments" on public.post_comments;
create policy "users add comments" on public.post_comments
  for insert to authenticated with check (auth.uid() = user_id and public.has_activity_access(10));

drop policy if exists "users add own content comments" on public.content_comments;
create policy "users add own content comments" on public.content_comments
  for insert to authenticated with check (auth.uid() = user_id and public.has_activity_access(10));

drop policy if exists "users publish own whispers" on public.whispers;
create policy "users publish own whispers" on public.whispers
  for insert to authenticated with check (auth.uid() = user_id and public.has_activity_access(10));

-- Daily heatmap, one-level whisper replies and administrator-managed inspiration templates.
alter table public.whispers add column if not exists parent_id uuid references public.whispers(id) on delete cascade;
create index if not exists whispers_parent_id_idx on public.whispers (parent_id);

create or replace function public.validate_whisper_reply_depth()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.parent_id is not null and exists (
    select 1 from public.whispers where id = new.parent_id and parent_id is not null
  ) then
    raise exception '碎碎念最多只能回复一层';
  end if;
  return new;
end;
$$;
drop trigger if exists validate_whisper_reply_depth_trigger on public.whispers;
create trigger validate_whisper_reply_depth_trigger before insert or update of parent_id on public.whispers
  for each row execute function public.validate_whisper_reply_depth();

create table if not exists public.whisper_templates (
  id uuid primary key default gen_random_uuid(),
  content text not null check (char_length(trim(content)) between 1 and 120),
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.whisper_templates enable row level security;
grant select on public.whisper_templates to authenticated;
grant insert, update, delete on public.whisper_templates to authenticated;
drop policy if exists "logged users read whisper templates" on public.whisper_templates;
drop policy if exists "admins manage whisper templates" on public.whisper_templates;
create policy "logged users read whisper templates" on public.whisper_templates
  for select to authenticated using (true);
create policy "admins manage whisper templates" on public.whisper_templates
  for all to authenticated using (public.is_blog_admin()) with check (public.is_blog_admin());

insert into public.whisper_templates (content, sort_order)
select seed.content, seed.sort_order from (values
  ('今天午饭吃的是：', 10), ('我今天发现：', 20), ('今天干了什么：', 30),
  ('今天遇到的好事：', 40), ('打算去做什么：', 50), ('几点起床：', 60),
  ('她是怎样的人：', 70), ('想对某人说的话：', 80)
) as seed(content, sort_order)
where not exists (select 1 from public.whisper_templates t where t.content = seed.content);

create or replace function public.get_user_activity_summary(p_user_id uuid)
returns table(score integer, title text)
language sql stable security definer set search_path = public as $$
  select coalesce(public.calculate_user_activity(p_user_id), 0),
    public.activity_title(coalesce(public.calculate_user_activity(p_user_id), 0));
$$;

create or replace function public.get_activity_heatmap(p_user_id uuid default null)
returns table(activity_date date, activity_count integer)
language sql stable security definer set search_path = public as $$
  with events as (
    select user_id, created_at from public.posts
    union all select user_id, created_at from public.moments
    union all select user_id, created_at from public.progress_logs
    union all select user_id, created_at from public.post_likes
    union all select user_id, created_at from public.content_likes
    union all select user_id, created_at from public.post_comments
    union all select user_id, created_at from public.content_comments
    union all select user_id, created_at from public.whispers
    union all select user_id, created_at from public.activity_checkins
  )
  select (created_at at time zone 'Asia/Shanghai')::date,
    count(*)::integer
  from events
  where (p_user_id is null or user_id = p_user_id)
    and created_at >= ((now() at time zone 'Asia/Shanghai')::date - 364)::timestamp
  group by 1 order by 1;
$$;

grant execute on function public.get_user_activity_summary(uuid) to anon, authenticated;
grant execute on function public.get_activity_heatmap(uuid) to anon, authenticated;

create or replace function public.get_public_whisper_summary(p_user_id uuid)
returns table(total_count bigint, previews jsonb)
language sql stable security definer set search_path = public as $$
  with recent as (
    select content, created_at from public.whispers
    where user_id = p_user_id and parent_id is null
    order by created_at desc limit 1
  ), totals as (
    select count(*)::bigint as total_count from public.whispers
    where user_id = p_user_id and parent_id is null
  )
  select totals.total_count,
    coalesce(jsonb_agg(jsonb_build_object('content', recent.content, 'created_at', recent.created_at)
      order by recent.created_at desc) filter (where recent.created_at is not null), '[]'::jsonb)
  from totals left join recent on true group by totals.total_count;
$$;
grant execute on function public.get_public_whisper_summary(uuid) to anon, authenticated;

-- Public mini-game guests and administrator-managed friend links.
create table if not exists public.jump_game_guest_scores (
  guest_token text primary key check (char_length(guest_token) between 20 and 100),
  display_name text not null unique,
  best_score integer not null default 0 check (best_score between 0 and 1000000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.jump_game_guest_scores enable row level security;
grant select on public.jump_game_guest_scores to anon, authenticated;
drop policy if exists "guest jump scores are readable" on public.jump_game_guest_scores;
create policy "guest jump scores are readable" on public.jump_game_guest_scores for select using (true);

create or replace function public.submit_guest_jump_game_score(p_guest_token text, p_score integer)
returns table(guest_token text, display_name text, best_score integer)
language plpgsql security definer set search_path = public as $$
declare next_name text;
begin
  if p_guest_token is null or char_length(p_guest_token) < 20 or char_length(p_guest_token) > 100 then raise exception '游客身份无效'; end if;
  if p_score is null or p_score < 0 or p_score > 1000000 then raise exception '无效的游戏分数'; end if;
  select g.display_name into next_name from public.jump_game_guest_scores g where g.guest_token = p_guest_token;
  if next_name is null then
    next_name := '罗星人' || ((select count(*) from public.jump_game_guest_scores) + 1)::text;
  end if;
  insert into public.jump_game_guest_scores (guest_token, display_name, best_score, updated_at)
  values (p_guest_token, next_name, p_score, now())
  on conflict on constraint jump_game_guest_scores_pkey do update set
    best_score = greatest(public.jump_game_guest_scores.best_score, excluded.best_score),
    updated_at = case when excluded.best_score > public.jump_game_guest_scores.best_score then now() else public.jump_game_guest_scores.updated_at end;
  return query select g.guest_token, g.display_name, g.best_score from public.jump_game_guest_scores g where g.guest_token = p_guest_token;
end;
$$;

create or replace function public.list_jump_game_leaderboard(p_limit integer default 20)
returns table(player_key text, display_name text, avatar_url text, best_score integer, is_guest boolean)
language sql stable security definer set search_path = public as $$
  select * from (
    select 'user:' || s.user_id::text as player_key,
      coalesce(nullif(p.display_name, ''), '普通用户') as display_name,
      p.avatar_url as avatar_url,
      s.best_score as best_score,
      false as is_guest
    from public.jump_game_scores s left join public.profiles p on p.id = s.user_id
    union all
    select 'guest:' || g.guest_token as player_key,
      g.display_name as display_name,
      null::text as avatar_url,
      g.best_score as best_score,
      true as is_guest
    from public.jump_game_guest_scores g
  ) ranked order by best_score desc, display_name asc limit greatest(1, least(coalesce(p_limit, 20), 100));
$$;
grant execute on function public.submit_guest_jump_game_score(text, integer) to anon, authenticated;
grant execute on function public.list_jump_game_leaderboard(integer) to anon, authenticated;

create table if not exists public.friend_links (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 1 and 40),
  description text not null default '' check (char_length(description) <= 120),
  url text not null check (url ~* '^https?://'),
  icon_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.friend_links enable row level security;
grant select on public.friend_links to anon, authenticated;
grant insert, update, delete on public.friend_links to authenticated;
drop policy if exists "public read friend links" on public.friend_links;
drop policy if exists "admin manage friend links" on public.friend_links;
create policy "public read friend links" on public.friend_links for select using (true);
create policy "admin manage friend links" on public.friend_links for all to authenticated using (public.is_blog_admin()) with check (public.is_blog_admin());
