-- Run this file once in Supabase SQL Editor.
-- Adds homepage announcement, life/progress comments, and admin storage usage.

alter table public.profiles add column if not exists announcement text not null default '';

create table if not exists public.content_comments (
  id uuid primary key default gen_random_uuid(),
  content_type text not null check (content_type in ('moment', 'progress')),
  content_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.content_likes (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('moment', 'progress')),
  content_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (content_type, content_id, user_id)
);

create table if not exists public.content_views (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('moment', 'progress')),
  content_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (content_type, content_id, user_id)
);

create index if not exists content_comments_lookup_idx
  on public.content_comments (content_type, content_id, created_at desc);

grant select on public.content_comments to anon, authenticated;
grant insert on public.content_comments to authenticated;
grant delete on public.content_comments to authenticated;
grant select on public.content_likes, public.content_views to anon, authenticated;
grant insert, delete on public.content_likes to authenticated;
grant insert on public.content_views to authenticated;
grant usage, select on all sequences in schema public to authenticated;
alter table public.content_comments enable row level security;
alter table public.content_likes enable row level security;
alter table public.content_views enable row level security;

drop policy if exists "content comments are readable" on public.content_comments;
drop policy if exists "users add own content comments" on public.content_comments;
drop policy if exists "admin deletes content comments" on public.content_comments;
create policy "content comments are readable" on public.content_comments for select using (true);
create policy "users add own content comments" on public.content_comments
  for insert to authenticated with check (auth.uid() = user_id);
create policy "admin deletes content comments" on public.content_comments for delete to authenticated using (public.is_blog_admin());

drop policy if exists "content likes are readable" on public.content_likes;
drop policy if exists "users manage own content likes" on public.content_likes;
create policy "content likes are readable" on public.content_likes for select using (true);
create policy "users manage own content likes" on public.content_likes for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "content views are readable" on public.content_views;
drop policy if exists "users add own content views" on public.content_views;
create policy "content views are readable" on public.content_views for select using (true);
create policy "users add own content views" on public.content_views for insert to authenticated with check (auth.uid() = user_id);

create or replace function public.get_blog_storage_usage()
returns bigint
language sql
stable
security definer
set search_path = public, storage
as $$
  select case when public.is_blog_admin() then coalesce(sum((metadata->>'size')::bigint), 0) else 0 end
  from storage.objects
  where bucket_id = 'xiaoluo-media';
$$;

revoke all on function public.get_blog_storage_usage() from public;
grant execute on function public.get_blog_storage_usage() to authenticated;
