-- Run this file once in Supabase SQL Editor.
-- Adds real likes, comments, and per-user post view tracking.

create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create table if not exists public.post_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_views (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

grant select on public.post_likes, public.post_comments, public.post_views to anon, authenticated;
grant insert, delete on public.post_likes to authenticated;
grant insert on public.post_comments to authenticated;
grant delete on public.post_comments to authenticated;
grant insert on public.post_views to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.post_likes enable row level security;
alter table public.post_comments enable row level security;
alter table public.post_views enable row level security;

drop policy if exists "likes are readable" on public.post_likes;
drop policy if exists "users manage own likes" on public.post_likes;
create policy "likes are readable" on public.post_likes for select using (true);
create policy "users manage own likes" on public.post_likes for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "comments are readable" on public.post_comments;
drop policy if exists "users add comments" on public.post_comments;
drop policy if exists "users edit own comments" on public.post_comments;
drop policy if exists "admin deletes post comments" on public.post_comments;
create policy "comments are readable" on public.post_comments for select using (true);
create policy "users add comments" on public.post_comments for insert to authenticated with check (auth.uid() = user_id);
create policy "users edit own comments" on public.post_comments for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "admin deletes post comments" on public.post_comments for delete to authenticated using (public.is_blog_admin());

drop policy if exists "views are readable" on public.post_views;
drop policy if exists "users add own views" on public.post_views;
create policy "views are readable" on public.post_views for select using (true);
create policy "users add own views" on public.post_views for insert to authenticated with check (auth.uid() = user_id);
