create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  phone text unique,
  email text unique,
  display_name text default 'Xiao Luo',
  avatar_url text,
  home_title text default 'XiaoLuo Blog',
  home_bio text default 'Welcome to XiaoLuo Blog.',
  home_background_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  page_path text not null,
  user_agent text,
  created_at timestamptz default now()
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  content text,
  cover_url text,
  category text,
  tags jsonb not null default '[]'::jsonb,
  attachments jsonb not null default '[]'::jsonb,
  min_activity_score integer not null default 0 check (min_activity_score >= 0),
  status text default 'published' check (status in ('draft', 'published', 'private')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.posts add column if not exists category text;
alter table public.posts add column if not exists tags jsonb not null default '[]'::jsonb;
alter table public.posts add column if not exists attachments jsonb not null default '[]'::jsonb;
alter table public.posts add column if not exists music_attachment jsonb;
alter table public.posts add column if not exists min_activity_score integer not null default 0;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists public.tags (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.page_views enable row level security;
alter table public.posts enable row level security;
alter table public.categories enable row level security;
alter table public.tags enable row level security;

drop policy if exists "profiles are readable" on public.profiles;
drop policy if exists "users update own profile" on public.profiles;
drop policy if exists "users insert own profile" on public.profiles;
drop policy if exists "anyone can insert page views" on public.page_views;
drop policy if exists "only authenticated can read page views" on public.page_views;
drop policy if exists "published posts are readable" on public.posts;
drop policy if exists "users manage own posts" on public.posts;
drop policy if exists "categories are readable" on public.categories;
drop policy if exists "users manage own categories" on public.categories;
drop policy if exists "tags are readable" on public.tags;
drop policy if exists "users manage own tags" on public.tags;

create policy "profiles are readable" on public.profiles
  for select using (true);

create policy "users update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "users insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

create policy "anyone can insert page views" on public.page_views
  for insert with check (true);

create policy "only authenticated can read page views" on public.page_views
  for select using (auth.role() = 'authenticated');

create policy "published posts are readable" on public.posts
  for select using (status = 'published' or auth.uid() = user_id);

create policy "users manage own posts" on public.posts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "categories are readable" on public.categories
  for select using (true);

create policy "users manage own categories" on public.categories
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "tags are readable" on public.tags
  for select using (true);

create policy "users manage own tags" on public.tags
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Blog profile extras and dashboard content.
alter table public.profiles add column if not exists contacts jsonb not null default '{}'::jsonb;

create table if not exists public.albums (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  meta text,
  description text,
  image_urls jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text,
  entry_date date not null default current_date,
  image_urls jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.progress_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text,
  entry_date date not null default current_date,
  image_urls jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.albums enable row level security;
alter table public.moments enable row level security;
alter table public.progress_logs enable row level security;

drop policy if exists "albums are readable" on public.albums;
drop policy if exists "users manage own albums" on public.albums;
drop policy if exists "moments are readable" on public.moments;
drop policy if exists "users manage own moments" on public.moments;
drop policy if exists "progress logs are readable" on public.progress_logs;
drop policy if exists "users manage own progress logs" on public.progress_logs;

create policy "albums are readable" on public.albums for select using (true);
create policy "users manage own albums" on public.albums for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "moments are readable" on public.moments for select using (true);
create policy "users manage own moments" on public.moments for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "progress logs are readable" on public.progress_logs for select using (true);
create policy "users manage own progress logs" on public.progress_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('xiaoluo-media', 'xiaoluo-media', true)
on conflict (id) do update set public = true;

drop policy if exists "public can read blog media" on storage.objects;
drop policy if exists "users upload own blog media" on storage.objects;
drop policy if exists "users update own blog media" on storage.objects;
drop policy if exists "users delete own blog media" on storage.objects;

create policy "public can read blog media" on storage.objects
  for select using (bucket_id = 'xiaoluo-media');
create policy "users upload own blog media" on storage.objects
  for insert to authenticated with check (bucket_id = 'xiaoluo-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users update own blog media" on storage.objects
  for update to authenticated using (bucket_id = 'xiaoluo-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users delete own blog media" on storage.objects
  for delete to authenticated using (bucket_id = 'xiaoluo-media' and (storage.foldername(name))[1] = auth.uid()::text);

-- Repair existing projects that already contain a profile row created before the policy existed.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.profiles to authenticated;
drop policy if exists "users manage own profile" on public.profiles;
create policy "users manage own profile" on public.profiles
  for all to authenticated using (auth.uid() = id) with check (auth.uid() = id);
