# -*- coding: utf-8 -*-
# 360 个高频英语词组 · 10 类
# 格式: (英文, 中文释义, 类别)
PHRASES = [
    # ========== A. 日常问候与礼貌 (50) ==========
    ("Hello!", "你好！", "日常问候与礼貌"),
    ("Hi!", "嗨！", "日常问候与礼貌"),
    ("Good morning.", "早上好。", "日常问候与礼貌"),
    ("Good afternoon.", "下午好。", "日常问候与礼貌"),
    ("Good evening.", "晚上好。", "日常问候与礼貌"),
    ("Good night.", "晚安。", "日常问候与礼貌"),
    ("How are you?", "你好吗？", "日常问候与礼貌"),
    ("I'm fine, thank you.", "我很好，谢谢。", "日常问候与礼貌"),
    ("Nice to meet you.", "很高兴认识你。", "日常问候与礼貌"),
    ("Nice to meet you too.", "我也很高兴认识你。", "日常问候与礼貌"),
    ("How do you do?", "您好。", "日常问候与礼貌"),
    ("Long time no see.", "好久不见。", "日常问候与礼貌"),
    ("What's up?", "最近怎么样？", "日常问候与礼貌"),
    ("How's it going?", "近况如何？", "日常问候与礼貌"),
    ("See you later.", "回头见。", "日常问候与礼貌"),
    ("See you tomorrow.", "明天见。", "日常问候与礼貌"),
    ("Goodbye!", "再见！", "日常问候与礼貌"),
    ("Have a nice day.", "祝你今天愉快。", "日常问候与礼貌"),
    ("Take care.", "保重。", "日常问候与礼貌"),
    ("Welcome!", "欢迎！", "日常问候与礼貌"),
    ("Please.", "请。", "日常问候与礼貌"),
    ("Thank you.", "谢谢你。", "日常问候与礼貌"),
    ("Thanks a lot.", "非常感谢。", "日常问候与礼貌"),
    ("Thank you very much.", "非常感谢。", "日常问候与礼貌"),
    ("You're welcome.", "不客气。", "日常问候与礼貌"),
    ("My pleasure.", "我的荣幸。", "日常问候与礼貌"),
    ("Sorry.", "对不起。", "日常问候与礼貌"),
    ("I'm sorry.", "我很抱歉。", "日常问候与礼貌"),
    ("Excuse me.", "打扰一下。", "日常问候与礼貌"),
    ("Pardon me.", "请再说一遍。", "日常问候与礼貌"),
    ("That's all right.", "没关系。", "日常问候与礼貌"),
    ("No problem.", "没问题。", "日常问候与礼貌"),
    ("It doesn't matter.", "没关系。", "日常问候与礼貌"),
    ("Never mind.", "别在意。", "日常问候与礼貌"),
    ("Congratulations!", "恭喜！", "日常问候与礼貌"),
    ("Happy birthday!", "生日快乐！", "日常问候与礼貌"),
    ("Good luck!", "祝你好运！", "日常问候与礼貌"),
    ("Cheers!", "干杯！", "日常问候与礼貌"),
    ("Bless you.", "保佑你。", "日常问候与礼貌"),
    ("After you.", "您先请。", "日常问候与礼貌"),
    ("Help yourself.", "请自便。", "日常问候与礼貌"),
    ("Make yourself at home.", "别客气，当自己家。", "日常问候与礼貌"),
    ("Same to you.", "你也一样。", "日常问候与礼貌"),
    ("Well done!", "干得好！", "日常问候与礼貌"),
    ("Good job!", "做得好！", "日常问候与礼貌"),
    ("All the best.", "一切顺利。", "日常问候与礼貌"),
    ("Have a good trip.", "旅途愉快。", "日常问候与礼貌"),
    ("Enjoy your meal.", "请慢用。", "日常问候与礼貌"),
    ("See you around.", "回头见。", "日常问候与礼貌"),
    ("Keep in touch.", "保持联系。", "日常问候与礼貌"),

    # ========== B. 饮食相关 (30) ==========
    ("I'm hungry.", "我饿了。", "饮食相关"),
    ("I'm thirsty.", "我渴了。", "饮食相关"),
    ("I'm full.", "我吃饱了。", "饮食相关"),
    ("What would you like to eat?", "你想吃什么？", "饮食相关"),
    ("I'd like a cup of coffee.", "我想要一杯咖啡。", "饮食相关"),
    ("A glass of water, please.", "请给我一杯水。", "饮食相关"),
    ("Could I see the menu?", "我可以看一下菜单吗？", "饮食相关"),
    ("What's today's special?", "今天有什么特色菜？", "饮食相关"),
    ("I'd like to order.", "我想点餐。", "饮食相关"),
    ("I'll have this one.", "我要这个。", "饮食相关"),
    ("How would you like your steak?", "您的牛排要几分熟？", "饮食相关"),
    ("Medium, please.", "五分熟，谢谢。", "饮食相关"),
    ("It tastes delicious.", "味道好极了。", "饮食相关"),
    ("It's too spicy.", "太辣了。", "饮食相关"),
    ("Could you pass the salt?", "能把盐递给我吗？", "饮食相关"),
    ("Would you like some more?", "再来一点吗？", "饮食相关"),
    ("I'm on a diet.", "我在节食。", "饮食相关"),
    ("I don't eat meat.", "我不吃肉。", "饮食相关"),
    ("I have an allergy to nuts.", "我对坚果过敏。", "饮食相关"),
    ("The bill, please.", "请结账。", "饮食相关"),
    ("Can I pay by card?", "我能刷卡吗？", "饮食相关"),
    ("Let's split the bill.", "我们AA制吧。", "饮食相关"),
    ("It's my treat.", "我请客。", "饮食相关"),
    ("Take it away, please.", "请打包带走。", "饮食相关"),
    ("Table for two, please.", "两位，谢谢。", "饮食相关"),
    ("A table by the window.", "靠窗的桌子。", "饮食相关"),
    ("Is there a table available?", "有位子吗？", "饮食相关"),
    ("Could I have some water?", "能给我点水吗？", "饮食相关"),
    ("Breakfast is ready.", "早饭好了。", "饮食相关"),
    ("Dinner is served.", "晚饭上桌了。", "饮食相关"),

    # ========== C. 购物与服装 (30) ==========
    ("How much is it?", "多少钱？", "购物与服装"),
    ("How much are these?", "这些多少钱？", "购物与服装"),
    ("It's too expensive.", "太贵了。", "购物与服装"),
    ("Can you make it cheaper?", "能便宜点吗？", "购物与服装"),
    ("Do you have a discount?", "有折扣吗？", "购物与服装"),
    ("I'm just looking.", "我只是随便看看。", "购物与服装"),
    ("Can I help you?", "需要帮忙吗？", "购物与服装"),
    ("I'd like to buy this.", "我想买这个。", "购物与服装"),
    ("Do you have this in a larger size?", "有大一码的吗？", "购物与服装"),
    ("Can I try it on?", "我能试穿吗？", "购物与服装"),
    ("Where is the fitting room?", "试衣间在哪里？", "购物与服装"),
    ("It fits me well.", "很合身。", "购物与服装"),
    ("It doesn't fit.", "不合身。", "购物与服装"),
    ("This is my size.", "这是我的尺码。", "购物与服装"),
    ("I'll take it.", "我买了。", "购物与服装"),
    ("Could you wrap it up?", "能帮我包起来吗？", "购物与服装"),
    ("I'd like a refund.", "我想退款。", "购物与服装"),
    ("Can I exchange it?", "能换一件吗？", "购物与服装"),
    ("Do you have a receipt?", "你有收据吗？", "购物与服装"),
    ("Cash or card?", "现金还是刷卡？", "购物与服装"),
    ("I'll pay in cash.", "我用现金支付。", "购物与服装"),
    ("Keep the change.", "不用找零了。", "购物与服装"),
    ("Is it on sale?", "这个在打折吗？", "购物与服装"),
    ("What color do you prefer?", "你喜欢什么颜色？", "购物与服装"),
    ("This color suits you.", "这个颜色适合你。", "购物与服装"),
    ("Where is the checkout?", "收银台在哪里？", "购物与服装"),
    ("Do you deliver?", "你们送货吗？", "购物与服装"),
    ("Shopping is my favorite.", "逛街是我的最爱。", "购物与服装"),
    ("It's a good deal.", "很划算。", "购物与服装"),
    ("The quality is great.", "质量很好。", "购物与服装"),

    # ========== D. 出行与方向 (35) ==========
    ("Excuse me, where is the station?", "请问车站在哪里？", "出行与方向"),
    ("How can I get there?", "我怎么去那里？", "出行与方向"),
    ("Which bus goes to the airport?", "哪路公交去机场？", "出行与方向"),
    ("Where can I catch a taxi?", "我在哪里能打到出租车？", "出行与方向"),
    ("How long does it take?", "要花多长时间？", "出行与方向"),
    ("How far is it?", "有多远？", "出行与方向"),
    ("It's not far.", "不远。", "出行与方向"),
    ("It's about ten minutes on foot.", "步行大约十分钟。", "出行与方向"),
    ("Turn left at the corner.", "在拐角处左转。", "出行与方向"),
    ("Turn right.", "右转。", "出行与方向"),
    ("Go straight ahead.", "一直往前走。", "出行与方向"),
    ("It's on your left.", "在你的左边。", "出行与方向"),
    ("It's on your right.", "在你的右边。", "出行与方向"),
    ("Is it near here?", "在这附近吗？", "出行与方向"),
    ("Could you show me on the map?", "你能在地图上指给我看吗？", "出行与方向"),
    ("I'm lost.", "我迷路了。", "出行与方向"),
    ("Can you help me?", "你能帮我吗？", "出行与方向"),
    ("Where is the nearest subway station?", "最近的地铁站在哪里？", "出行与方向"),
    ("Which line should I take?", "我应该坐哪条线？", "出行与方向"),
    ("A ticket to the city center, please.", "请给我一张去市中心的票。", "出行与方向"),
    ("How much is the fare?", "车费多少钱？", "出行与方向"),
    ("Where should I get off?", "我该在哪里下车？", "出行与方向"),
    ("Is this seat taken?", "这个座位有人吗？", "出行与方向"),
    ("The bus is coming.", "公交车来了。", "出行与方向"),
    ("We need to hurry.", "我们得抓紧了。", "出行与方向"),
    ("We're going to be late.", "我们要迟到了。", "出行与方向"),
    ("Have a safe trip.", "一路平安。", "出行与方向"),
    ("Check in, please.", "请办理登机手续。", "出行与方向"),
    ("Where is the boarding gate?", "登机口在哪里？", "出行与方向"),
    ("What time does the flight leave?", "航班几点起飞？", "出行与方向"),
    ("Where is my luggage?", "我的行李在哪里？", "出行与方向"),
    ("I need a hotel room.", "我需要一个酒店房间。", "出行与方向"),
    ("I have a reservation.", "我有预订。", "出行与方向"),
    ("How do I get to the hotel?", "我怎么去酒店？", "出行与方向"),
    ("Which way is the north?", "哪边是北？", "出行与方向"),

    # ========== E. 居住与居家 (25) ==========
    ("Welcome to my home.", "欢迎来我家。", "居住与居家"),
    ("Come in, please.", "请进。", "居住与居家"),
    ("Please take off your shoes.", "请脱鞋。", "居住与居家"),
    ("Where is the bathroom?", "洗手间在哪里？", "居住与居家"),
    ("This is my bedroom.", "这是我的卧室。", "居住与居家"),
    ("My room is on the third floor.", "我的房间在三楼。", "居住与居家"),
    ("Turn on the light.", "开灯。", "居住与居家"),
    ("Turn off the light.", "关灯。", "居住与居家"),
    ("Open the window.", "打开窗户。", "居住与居家"),
    ("Close the door.", "关门。", "居住与居家"),
    ("Lock the door.", "锁门。", "居住与居家"),
    ("Set the alarm.", "设闹钟。", "居住与居家"),
    ("I'm moving to a new place.", "我要搬新家了。", "居住与居家"),
    ("The rent is 2000 a month.", "房租每月2000元。", "居住与居家"),
    ("It's time to get up.", "该起床了。", "居住与居家"),
    ("Time for bed.", "该睡觉了。", "居住与居家"),
    ("I need to do the laundry.", "我需要洗衣服。", "居住与居家"),
    ("Hang the clothes out to dry.", "把衣服挂出去晾干。", "居住与居家"),
    ("The room is a mess.", "房间乱糟糟的。", "居住与居家"),
    ("Please clean up your room.", "请打扫你的房间。", "居住与居家"),
    ("Take out the garbage.", "倒垃圾。", "居住与居家"),
    ("Water the plants.", "给植物浇水。", "居住与居家"),
    ("Feed the cat.", "喂猫。", "居住与居家"),
    ("I'm home.", "我回来了。", "居住与居家"),
    ("Make the bed.", "铺床。", "居住与居家"),

    # ========== F. 感觉与情绪表达 (45) ==========
    ("I'm happy.", "我很开心。", "感觉与情绪表达"),
    ("I'm sad.", "我很难过。", "感觉与情绪表达"),
    ("I'm angry.", "我很生气。", "感觉与情绪表达"),
    ("I'm scared.", "我害怕。", "感觉与情绪表达"),
    ("I'm surprised.", "我很惊讶。", "感觉与情绪表达"),
    ("I'm excited.", "我很兴奋。", "感觉与情绪表达"),
    ("I'm nervous.", "我很紧张。", "感觉与情绪表达"),
    ("I'm worried about you.", "我担心你。", "感觉与情绪表达"),
    ("I'm tired.", "我累了。", "感觉与情绪表达"),
    ("I'm sleepy.", "我困了。", "感觉与情绪表达"),
    ("I'm bored.", "我很无聊。", "感觉与情绪表达"),
    ("I'm lonely.", "我很孤独。", "感觉与情绪表达"),
    ("I'm proud of you.", "我为你骄傲。", "感觉与情绪表达"),
    ("I'm shy.", "我害羞。", "感觉与情绪表达"),
    ("I'm disappointed.", "我很失望。", "感觉与情绪表达"),
    ("I'm frustrated.", "我很沮丧。", "感觉与情绪表达"),
    ("I'm confused.", "我很困惑。", "感觉与情绪表达"),
    ("I'm grateful.", "我很感激。", "感觉与情绪表达"),
    ("I'm stressed out.", "我压力很大。", "感觉与情绪表达"),
    ("I feel great.", "我感觉很好。", "感觉与情绪表达"),
    ("I feel terrible.", "我感觉糟透了。", "感觉与情绪表达"),
    ("I'm in a good mood.", "我心情很好。", "感觉与情绪表达"),
    ("I'm in a bad mood.", "我心情不好。", "感觉与情绪表达"),
    ("Cheer up!", "振作起来！", "感觉与情绪表达"),
    ("Calm down.", "冷静点。", "感觉与情绪表达"),
    ("Don't worry.", "别担心。", "感觉与情绪表达"),
    ("Take it easy.", "放轻松。", "感觉与情绪表达"),
    ("I can't wait!", "我等不及了！", "感觉与情绪表达"),
    ("I'm looking forward to it.", "我很期待。", "感觉与情绪表达"),
    ("It makes me happy.", "这让我开心。", "感觉与情绪表达"),
    ("It makes me angry.", "这让我生气。", "感觉与情绪表达"),
    ("I'm crazy about music.", "我对音乐着迷。", "感觉与情绪表达"),
    ("I'm interested in art.", "我对艺术感兴趣。", "感觉与情绪表达"),
    ("I'm good at swimming.", "我擅长游泳。", "感觉与情绪表达"),
    ("I'm bad at cooking.", "我不擅长做饭。", "感觉与情绪表达"),
    ("I miss you so much.", "我非常想你。", "感觉与情绪表达"),
    ("I love you.", "我爱你。", "感觉与情绪表达"),
    ("I like it a lot.", "我非常喜欢。", "感觉与情绪表达"),
    ("I don't like it at all.", "我一点也不喜欢。", "感觉与情绪表达"),
    ("It's amazing!", "太棒了！", "感觉与情绪表达"),
    ("That's awesome!", "太酷了！", "感觉与情绪表达"),
    ("That's too bad.", "太遗憾了。", "感觉与情绪表达"),
    ("What a pity!", "真可惜！", "感觉与情绪表达"),
    ("It's not a big deal.", "没什么大不了的。", "感觉与情绪表达"),
    ("It really touched me.", "这真的让我感动。", "感觉与情绪表达"),

    # ========== G. 表达需要与请求 (45) ==========
    ("I need some help.", "我需要帮助。", "表达需要与请求"),
    ("Could you help me?", "你能帮我吗？", "表达需要与请求"),
    ("Can I ask a question?", "我能问个问题吗？", "表达需要与请求"),
    ("May I come in?", "我能进来吗？", "表达需要与请求"),
    ("May I use your phone?", "我能用一下你的电话吗？", "表达需要与请求"),
    ("Could you speak more slowly?", "你能说慢一点吗？", "表达需要与请求"),
    ("Could you repeat that?", "你能再说一遍吗？", "表达需要与请求"),
    ("Would you mind opening the window?", "你介意开窗吗？", "表达需要与请求"),
    ("I'd like to make a request.", "我想提个请求。", "表达需要与请求"),
    ("I need to go to the bathroom.", "我需要去洗手间。", "表达需要与请求"),
    ("I need a break.", "我需要休息一下。", "表达需要与请求"),
    ("I need more time.", "我需要更多时间。", "表达需要与请求"),
    ("I have to leave now.", "我现在必须走了。", "表达需要与请求"),
    ("I have to get up early.", "我得早起。", "表达需要与请求"),
    ("I must finish this today.", "我今天必须完成这个。", "表达需要与请求"),
    ("I should go home.", "我应该回家了。", "表达需要与请求"),
    ("You should see a doctor.", "你应该去看医生。", "表达需要与请求"),
    ("Can I have a look?", "我能看一下吗？", "表达需要与请求"),
    ("Can I borrow your pen?", "我能借你的笔吗？", "表达需要与请求"),
    ("Could you give me a hand?", "你能帮我一把吗？", "表达需要与请求"),
    ("Would you like some tea?", "你想喝点茶吗？", "表达需要与请求"),
    ("What would you like?", "你想要什么？", "表达需要与请求"),
    ("I'd like to change my reservation.", "我想改一下预订。", "表达需要与请求"),
    ("I want to book a ticket.", "我想订张票。", "表达需要与请求"),
    ("I want to learn English.", "我想学英语。", "表达需要与请求"),
    ("I don't want to go.", "我不想去。", "表达需要与请求"),
    ("I'd rather stay home.", "我宁愿待在家里。", "表达需要与请求"),
    ("It's up to you.", "由你决定。", "表达需要与请求"),
    ("Please wait a moment.", "请稍等。", "表达需要与请求"),
    ("Just a second.", "稍等一下。", "表达需要与请求"),
    ("Hold on, please.", "请稍候。", "表达需要与请求"),
    ("Let me think about it.", "让我想想。", "表达需要与请求"),
    ("Let me check.", "让我查一下。", "表达需要与请求"),
    ("Do you mind if I smoke?", "你介意我抽烟吗？", "表达需要与请求"),
    ("Is it okay if I open the window?", "我开窗可以吗？", "表达需要与请求"),
    ("Could I get a glass of water?", "我能要杯水吗？", "表达需要与请求"),
    ("I was wondering if you could help.", "我想知道你能不能帮忙。", "表达需要与请求"),
    ("Would it be possible...?", "有可能……吗？", "表达需要与请求"),
    ("I'm afraid I can't.", "恐怕不行。", "表达需要与请求"),
    ("No, thanks.", "不了，谢谢。", "表达需要与请求"),
    ("Yes, please.", "好的，谢谢。", "表达需要与请求"),
    ("Go ahead.", "请便。", "表达需要与请求"),
    ("Of course.", "当然可以。", "表达需要与请求"),
    ("Sure, no problem.", "当然，没问题。", "表达需要与请求"),
    ("That would be great.", "那太好了。", "表达需要与请求"),

    # ========== H. 沟通与对话 (50) ==========
    ("What do you mean?", "你什么意思？", "沟通与对话"),
    ("What does this word mean?", "这个词什么意思？", "沟通与对话"),
    ("How do you say this in English?", "这个用英语怎么说？", "沟通与对话"),
    ("How do you spell it?", "怎么拼写？", "沟通与对话"),
    ("Could you write it down?", "你能写下来吗？", "沟通与对话"),
    ("Can you hear me?", "你能听到我吗？", "沟通与对话"),
    ("I can't hear you.", "我听不到你。", "沟通与对话"),
    ("Speak up, please.", "请大声点。", "沟通与对话"),
    ("I didn't catch that.", "我没听清。", "沟通与对话"),
    ("What did you say?", "你说什么？", "沟通与对话"),
    ("Let me think.", "让我想想。", "沟通与对话"),
    ("I see.", "我明白了。", "沟通与对话"),
    ("I got it.", "我懂了。", "沟通与对话"),
    ("I don't understand.", "我不明白。", "沟通与对话"),
    ("I don't know.", "我不知道。", "沟通与对话"),
    ("I have no idea.", "我完全不知道。", "沟通与对话"),
    ("Are you sure?", "你确定吗？", "沟通与对话"),
    ("I'm not sure.", "我不确定。", "沟通与对话"),
    ("I agree with you.", "我同意你。", "沟通与对话"),
    ("I don't agree.", "我不同意。", "沟通与对话"),
    ("That's a good idea.", "好主意。", "沟通与对话"),
    ("What do you think?", "你觉得呢？", "沟通与对话"),
    ("In my opinion...", "在我看来……", "沟通与对话"),
    ("Let's talk about it.", "我们谈谈吧。", "沟通与对话"),
    ("Let's change the topic.", "我们换个话题。", "沟通与对话"),
    ("Can we move on?", "我们能继续吗？", "沟通与对话"),
    ("To be honest...", "老实说……", "沟通与对话"),
    ("By the way...", "顺便说一下……", "沟通与对话"),
    ("For example...", "例如……", "沟通与对话"),
    ("That is to say...", "也就是说……", "沟通与对话"),
    ("In other words...", "换句话说……", "沟通与对话"),
    ("I'm kidding.", "我开玩笑的。", "沟通与对话"),
    ("Really?", "真的吗？", "沟通与对话"),
    ("Are you serious?", "你是认真的吗？", "沟通与对话"),
    ("I mean it.", "我是认真的。", "沟通与对话"),
    ("Let me explain.", "让我解释一下。", "沟通与对话"),
    ("Let me make it clear.", "让我说清楚。", "沟通与对话"),
    ("Long story short.", "长话短说。", "沟通与对话"),
    ("Don't interrupt me.", "别打断我。", "沟通与对话"),
    ("Can I say something?", "我能说几句吗？", "沟通与对话"),
    ("Let me finish.", "让我说完。", "沟通与对话"),
    ("That's what I mean.", "我就是这个意思。", "沟通与对话"),
    ("Is that clear?", "清楚了吗？", "沟通与对话"),
    ("Do you follow me?", "你跟得上吗？", "沟通与对话"),
    ("Got it?", "明白了吗？", "沟通与对话"),
    ("I'll tell you later.", "我以后再告诉你。", "沟通与对话"),
    ("Keep it a secret.", "保密。", "沟通与对话"),
    ("Tell me more.", "再多告诉我一些。", "沟通与对话"),
    ("Any questions?", "有问题吗？", "沟通与对话"),
    ("That's all.", "就这些。", "沟通与对话"),

    # ========== I. 时间与频率 (25) ==========
    ("What time is it?", "几点了？", "时间与频率"),
    ("It's half past seven.", "七点半了。", "时间与频率"),
    ("What day is it today?", "今天星期几？", "时间与频率"),
    ("What's the date today?", "今天几号？", "时间与频率"),
    ("I get up at seven.", "我七点起床。", "时间与频率"),
    ("See you at eight.", "八点见。", "时间与频率"),
    ("Just in time.", "刚好赶上。", "时间与频率"),
    ("On time.", "准时。", "时间与频率"),
    ("It's time to go.", "该走了。", "时间与频率"),
    ("The time is up.", "时间到了。", "时间与频率"),
    ("From now on.", "从现在起。", "时间与频率"),
    ("In the past.", "在过去。", "时间与频率"),
    ("In the future.", "在未来。", "时间与频率"),
    ("At the moment.", "此刻。", "时间与频率"),
    ("These days.", "这些天。", "时间与频率"),
    ("Once a week.", "每周一次。", "时间与频率"),
    ("Twice a month.", "每月两次。", "时间与频率"),
    ("Every day.", "每天。", "时间与频率"),
    ("Every other day.", "每隔一天。", "时间与频率"),
    ("Right now.", "立刻。", "时间与频率"),
    ("A long time ago.", "很久以前。", "时间与频率"),
    ("In a hurry.", "匆忙地。", "时间与频率"),
    ("All the time.", "一直。", "时间与频率"),
    ("Once in a while.", "偶尔。", "时间与频率"),
    ("Day by day.", "一天天地。", "时间与频率"),

    # ========== J. 常用动词短语 (25) ==========
    ("get up", "起床", "常用动词短语"),
    ("wake up", "醒来", "常用动词短语"),
    ("go out", "出去", "常用动词短语"),
    ("come back", "回来", "常用动词短语"),
    ("come in", "进来", "常用动词短语"),
    ("get on", "上车", "常用动词短语"),
    ("get off", "下车", "常用动词短语"),
    ("dress up", "打扮", "常用动词短语"),
    ("put off", "推迟", "常用动词短语"),
    ("turn on", "打开（电器）", "常用动词短语"),
    ("turn off", "关掉（电器）", "常用动词短语"),
    ("look for", "寻找", "常用动词短语"),
    ("find out", "查明", "常用动词短语"),
    ("give up", "放弃", "常用动词短语"),
    ("give back", "归还", "常用动词短语"),
    ("look after", "照顾", "常用动词短语"),
    ("look forward to", "期待", "常用动词短语"),
    ("take care of", "照顾", "常用动词短语"),
    ("get along with", "与……相处", "常用动词短语"),
    ("come up with", "想出", "常用动词短语"),
    ("run out of", "用完", "常用动词短语"),
    ("work out", "解决；锻炼", "常用动词短语"),
    ("hang out", "闲逛；出去玩", "常用动词短语"),
    ("show up", "出现", "常用动词短语"),
    ("break down", "出故障", "常用动词短语"),
]
